version: '3'
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: jejakpatroli
    container_name: jejakpatroli-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - jejakpatroli

  db:
    image: mysql:8.0
    container_name: jejakpatroli-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jejakpatroli
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - jejakpatroli

  nginx:
    image: nginx:1.21
    container_name: jejakpatroli-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - jejakpatroli

networks:
  jejakpatroli:
    driver: bridge

volumes:
  dbdata:
    driver: local