version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jejakpatroli_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: jejakpatroli_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: jejakpatroli
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.25-alpine
    container_name: jejakpatroli_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local