name: Laravel CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: jejakpatroli
          MYSQL_USER: root
          MYSQL_PASSWORD: ""
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer
        extension: mbstring, dom, fileinfo, pdo, pdo_mysql
    
    - name: Copy .env
      run: cp .env.example .env
    
    - name: Install Dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
    
    - name: Update Dependencies
      run: composer update --no-progress --prefer-dist --optimize-autoloader
    
    - name: Generate Application Key
      run: php artisan key:generate
    
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Update .env for MySQL
      run: |
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=jejakpatroli/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=""/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=127.0.0.1/' .env
    
    - name: Wait for MySQL to be ready
      run: |
        for i in `seq 1 10`; do
          mysqladmin ping -h 127.0.0.1 -u root --password="" --silent && break || sleep 10
        done
    
    - name: Run Migrations
      run: php artisan migrate --force
    
    - name: Execute Tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: jejakpatroli
        DB_USERNAME: user
        DB_PASSWORD: ""
        DB_HOST: mysql
      run: php artisan test
